LISTEN_ADDRESS: "0.0.0.0"
LISTEN_PORT: "8000"
DEVELOPMENT: "1"

COMMIT_SHA: "Unknown build"
PRODUCT_VERSION: "0.1-beta"

FIXTURES_TO_UPLOAD:
  - "openstack_folsom.json"
  - "start_notification.json"

DATABASE:
  engine: "postgresql"
  name: "nailgun"
  host: "localhost"
  port: "5432"
  user: "nailgun"
  passwd: "nailgun"

KEEPALIVE:
  interval: 30
  timeout: 180

STATIC_DIR: "/var/tmp/nailgun_static"
TEMPLATE_DIR: "/var/tmp/nailgun_static"
NETWORK_POOLS:
  public:
    - "240.0.0.0/16"
  private10:
    - "10.0.0.0/8"
  private172:
    - "172.16.0.0/12"
  private192:
    - "192.168.0.0/16"

NET_EXCLUDE:
  - "10.20.0.0/24"

VLANS_RANGE_START: "100"
VLANS_RANGE_END: "1000"

RABBITMQ:
  fake: "0"
  hostname: "127.0.0.1"

CUSTOM_LOG: &nailgun_log "/var/log/nailgun.log"
ACCESS_LOG: "/var/log/nailgun_access.log"

PATH_TO_SSH_KEY: = "/root/.ssh/id_rsa"
PATH_TO_BOOTSTRAP_SSH_KEY: "/root/.ssh/bootstrap.rsa"

COBBLER_URL: "http://localhost/cobbler_api"
COBBLER_USER: "cobbler"
COBBLER_PASSWORD: "cobbler"
COBBLER_PROFILE: "centos63-x86_64"

TRUNCATE_LOG_ENTRIES: 100
UI_LOG_DATE_FORMAT: '%Y-%m-%d %H:%M:%S'
LOG_FORMATS:
  - &remote_syslog_log_format
    regexp: '^(?P<date>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})\s(?P<level>[a-z]{3,7}):\s(?P<text>.*)$'
    date_format: '%Y-%m-%dT%H:%M:%S'
    levels:
      - DEBUG
      - INFO
      - NOTICE
      - WARNING
      - ERR
      - CRIT
      - ALERT
      - EMERG
  - &syslog_log_format
    regexp: '^(?P<ip>\d+\.\d+\.\d+\.\d+)\s+(?P<date>\w{3}\s+\d+\s+\d+:\d+:\d+)\s+(?P<fqdn>[\w\.\-]+)\s+(?P<component>[\w\.\-/]+):\s+(?:[\d:,]+\s+(?P<level>[A-Z]+)\s+)?(?:\s*:\s*)?(?P<text>.*)$'
    levels:
      - DEBUG
      - INFO
      - NOTICE
      - WARNING
      - ERR
      - CRIT
      - ALERT
      - EMERG
  - &python_log_format
    regexp: '^(?P<date>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}),\d{3}\s(?P<level>[A-Z]+)\s(?P<text>.*)$'
    date_format: '%Y-%m-%d %H:%M:%S'
    levels:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      - CRITICAL

LOG_TYPES:
  - &local_log_type
    remote: False
    multiline: True
  - &remote_log_type
    remote: True
    multiline: True
    base: '/var/log/remote/'

LOG_GROUPS:
  - &main_install_log_group
    group: ~
  - &install_log_group
    group: 'Other install logs'
  - &bootstrap_log_group
    group: 'Bootstrap logs'

LOGS:
# Master node logs.
  - id: nailgun
    name: "FuelWeb"
    <<: *local_log_type
    <<: *python_log_format
    path: *nailgun_log
  - id: naily
    name: "Orchestrator"
    <<: *local_log_type
    <<: *remote_syslog_log_format
    path: '/var/log/naily/naily.log'
# Fake target logs.
  - id: 'fake-target-mcollective'
    name: "mcollective"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *main_install_log_group
    fake: True
    path: '/var/tmp/fake-target-mcollective.log'
# Target node installation logs.
  - id: 'install/puppet'
    name: "puppet"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *main_install_log_group
    path: 'puppet-agent.log'
  - id: 'install/anaconda'
    name: "anaconda"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *main_install_log_group
    path: 'install/anaconda.log'
  - id: 'install/syslog'
    name: "syslog"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *main_install_log_group
    path: 'install/syslog.log'
  - id: 'install/storage'
    name: "storage"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *install_log_group
    path: 'install/storage.log'
  - id: 'install/ks-pre'
    name: "kickstart-pre"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *install_log_group
    path: 'install/ks-pre.log'
  - id: 'install/ks-post'
    name: "kickstart-post"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *install_log_group
    path: 'install/ks-post.log'
# Bootstrap node logs.
  - id: 'bootstrap/dmesg'
    name: "dmesg"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *bootstrap_log_group
    path: 'bootstrap/dmesg.log'
  - id: 'bootstrap/secure'
    name: "secure"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *bootstrap_log_group
    path: 'bootstrap/secure.log'
  - id: 'bootstrap/messages'
    name: "messages"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *bootstrap_log_group
    path: 'bootstrap/messages.log'
  - id: 'bootstrap/mco'
    name: "mcollective"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *bootstrap_log_group
    path: 'bootstrap/mcollective.log'
  - id: 'bootstrap/agent'
    name: "agent"
    <<: *remote_log_type
    <<: *remote_syslog_log_format
    <<: *bootstrap_log_group
    path: 'bootstrap/agent.log'

LOGS_TO_PACK_FOR_SUPPORT:
  logs: '/var/log'

MCO_PSKEY: "Gie6iega9ohngaenahthohngu8aebohxah9seidi"
MCO_STOMPHOST: "localhost"
MCO_STOMPPORT: "61613"
MCO_STOMPUSER: "guest"
MCO_STOMPPASSWORD: "guest"

PUPPET_MASTER_HOST: "localhost"
PUPPET_VERSION: "2.7.19"

DNS_DOMAIN: "example.com"
DNS_SERVERS: "127.0.0.1"
DNS_SEARCH: "example.com"

FAKE_TASKS_TICK_INTERVAL: "1"
FAKE_TASKS_TICK_COUNT: "30"
